### ISSUE TITLE
Framework 'UnityFramework' not found

### ISSUE THREAD

**Issue by Asim313** [azesmway/react-native-unity#136]
<img width="454" alt="Screenshot 2024-11-21 at 4 33 11 PM" src="https://github.com/user-attachments/assets/ad11d2a5-9b05-45ff-838c-cfdc24e47f7e">

I have added the build under unity/builds/ios/ but got this issue while react native build

@azesmway Please help me with this. I have followed all the steps and instructions for iOS.

**Comment by Asim313** [comment]
@TruAmbition I have followed every single step exactly as outlined in the following.
https://medium.com/@selvaannies/integrating-unity-into-react-native-ios-using-azesmway-react-native-unity-b09837a54a69

I think the issue might be related to a missing UnityFramework in unityfamework.framework folder, but I'm not entirely sure of the exact problem.

**Comment by TruAmbition** [comment]
Can you please confirm the version of Unity, MacOS and Xcode you are using?

**Comment by Asim313** [comment]
> Can you please confirm the version of Unity, MacOS and Xcode you are using?

MacOS : 14.5 (23F79)
XCode : 15.4
React Native : 0.75.2
Unity6: 6000.0.26f1

**Comment by TruAmbition** [comment]
We haven't officially confirmed support for Unity6 just yet. However, we have had someone confirm things are working with the latest changes we have staged to fix issues with Xcode 16.

You can find that information regarding their tech stack [here](https://github.com/azesmway/react-native-unity/pull/133#issuecomment-2488436184). Please note, these changes will be applied and released on version 1.0.11, we are in final stages of checkout after and hope to have release as early as next week. Note, this fix is not intended to work with Unity6, however it appears developers have confirmed it working without any breaking changes.  Please also note his remarks about cocoa pod version.

**Comment by Asim313** [comment]
Okay i will give you feedback ASAP

**Comment by TruAmbition** [comment]
@Asim313 Sure thing, give me a moment to test and get back to. However if the Unity framework already being zipped. Idk if I'll get a different result. If you want to frame out a project in Unity and send me the Unity project. I can see if I can get it to run in a fresh react project. If so, I can send that to you. Let me know. I'll do my best to replicate your build setup. I have both Intel and arm based Macs for checkout.

**Comment by Asim313** [comment]
@TruAmbition I'm so happy and deeply grateful for your thoughtful response. Your dedication and effort truly stand out, and I sincerely appreciate the hard work you put into helping me.

Here is my orignal unity project.
https://we.tl/t-uuGszyA83u

**Comment by Asim313** [comment]
Okay no problem. Take your time 😊

**Comment by TruAmbition** [comment]
Hey @Asim313, just wanted to let you know that I was able to reproduce your error after installing the necessary dependencies for the UnityView to work. I'm going to play with it more tomorrow. Been a long day so I'm pretty tired. I think I did notice in your Unity project you are missing the assets/plugins/iOS directory with all the scripts provided in the repository example directory. 

I don't think that was the problem you were facing though. I just created a new Unity project with the same version and a fresh react project. I got the Unity framework imported and was able to build the react native app correctly. Things didn't turn until I started installing the rest of the dependencies. Just wanted to give you a quick update, I think it's fixable for sure, just need a good night sleep before checking again. I'll be in touch, Thank you kindly for your patience.

**Comment by Asim313** [comment]
@TruAmbition I have added the iOS plugin (including NativeCallProxy files) under the Assets/Plugins directory and generated a build for Xcode. Following that, I created the UnityFramework build as per the instructions but encountered an error.

Could you integrate the iOS plugin into the provided Unity project and complete the process for me?

**Comment by Asim313** [comment]
@TruAmbition I'm waiting for your response.

**Comment by TruAmbition** [comment]
Hey @Asim313 sorry, I got sick and was unable to do as much as I wanted. Originally I was hoping to get your project working. But the issue was discovered with a fresh react native project + Unity 6 project. I think for now, This will be a long running issue that we will hope to resolve. I hope that you will continue troubleshooting and share any findings with the community. I plan to do the same with a lighter week ahead. Thank you for your patience

**Comment by Asim313** [comment]
@TruAmbition I have created a new unity project and try to integrate with ios.
got error: Undefined symbol: __mh_dylib_header
can you help me out?

**Comment by TruAmbition** [comment]
Yes. This is the issue fixed in 1.0.11. Unfortunately we are still pending the package update to NPM. If you would like to, you can use my fork in the meantime. If so, in your package.json use this line instead:

"@azesmway/react-native-unity": "github:TruAmbition/react-native-unity#v1.0.11"

This will use my fork that has the 1.0.11 fix.

Sorry for the inconvenience, we will try and get the NPM package updated asap. 

Let me know how it goes after this if you would please.

Thanks

**Comment by Asim313** [comment]
@TruAmbition getting same issue with this updated code.
"@azesmway/react-native-unity": "github:TruAmbition/react-native-unity#v1.0.11"

error: Undefined symbol: __mh_dylib_header

**Comment by Asim313** [comment]
@TruAmbition 
here is the exact error:

Undefined symbols for architecture x86_64:
  "__mh_dylib_header", referenced from:
      UnityFrameworkLoad() in libreact-native-unity.a[2](RNUnityView.o)

**Comment by TruAmbition** [comment]
@Asim313 

"@azesmway/react-native-unity": "github:TruAmbition/react-native-unity#v1.0.11"
and
rm -rf ios/Pods && rm -f ios/Podfile.lock && npx pod-install

Sorry, forgot the very import rebuilding of pods step.

**Comment by Asim313** [comment]
@TruAmbition Already tried but same error

**Comment by Asim313** [comment]
https://github.com/azesmway/react-native-unity/issues/139 there issue is diffent from my this issue:

Undefined symbols for architecture x86_64:
"__mh_dylib_header", referenced from:
UnityFrameworkLoad() in libreact-native-unity.a[2](https://github.com/azesmway/react-native-unity/issues/RNUnityView.o)

**Comment by TruAmbition** [comment]
Are you still trying with Unity6? 

I would say try without unity 6 until
We can get the bugs fixed. This flow should work for Unity 2022.3.x

I user Unity 2022.3.46f1

**Comment by Asim313** [comment]
Yes, I'm using unity6

**Comment by omprakash6054** [comment]
<img width="806" alt="Screenshot 2024-11-29 at 09 01 36" src="https://github.com/user-attachments/assets/288ed25d-51f6-48bd-8f65-887464c7ef3e">
I have an issue someone can help me?

I'm using unity 2021.8.3f1 and this is a react native and unity project.

**Comment by omprakash6054** [comment]
<img width="806" alt="Screenshot 2024-11-29 at 09 41 43" src="https://github.com/user-attachments/assets/85457eaf-c8c6-4de9-9f64-80402e413437">

This are my build settings

**Comment by omprakash6054** [comment]
<img width="806" alt="Screenshot 2024-11-29 at 09 42 33" src="https://github.com/user-attachments/assets/911824de-f609-45c8-8b7f-335c271915f2">

**Comment by tovgroliv** [comment]
> Yes, I'm using unity6

Rebuild is required

**Comment by asrasoft-admin** [comment]
@TruAmbition Are you available for a short zoom meeting?

**Comment by Asim313** [comment]
@TruAmbition Are you available for a short meeting(zoom)?

**Comment by TruAmbition** [comment]
> @TruAmbition Are you available for a short meeting(zoom)?

Hi @Asim313 I am not, Thank you for asking. Please note that the latest version 1.0.11 is not published to NPM. I hope this helps you along your journey. We plan to look more into Unity6 at the top of the year. Please share any findings you do have.

kind regards,

**Comment by gyanani-ritika** [comment]
Facing the same issue.. @TruAmbition  should we use the unity 6000 or not? 
and by using unity (2022.3.55f1) Silicon, would our problems be solved in android and ios while using Unity (6000.0.32f1)?

**Comment by TruAmbition** [comment]
> while using Unity (6000.0.32f1)?

@gyanani-ritika yes, assuming you are getting this error. This project currently hasn't been validated/updated to work with Unity 6 just yet. Please continue to use a pre-Unity6, LTS version of Unity. This should solve the issue for you as long as you have the latest version of the npm package (1.0.11) installed and Xcode 16.x

I hope this helps.

**Comment by TruAmbition** [comment]
Closing this as we currently do not support Unity 6.

**Comment by Pavaneshpratap** [comment]
> [#139](https://github.com/azesmway/react-native-unity/issues/139) there issue is diffent from my this issue:
> 
> Undefined symbols for architecture x86_64: "__mh_dylib_header", referenced from: UnityFrameworkLoad() in libreact-native-unity.a[2](https://github.com/azesmway/react-native-unity/issues/RNUnityView.o)


I'm still experiencing this issue. Is there any update on its resolution?
